### ISSUE TITLE
ValueError: There's already an active RQ scheduler

### ISSUE THREAD

**Issue by dcloud** [CSIS-iLab/new-silk-road#98]
https://sentry.io/csis/recon-asia/issues/167866733/

```
ValueError: There's already an active RQ scheduler
(4 additional frame(s) were not displayed)
...
  File "django_rq/management/commands/rqscheduler.py", line 22, in handle
    scheduler.run()

ValueError: There's already an active RQ scheduler
```

Looks like a side effect of heroku starting new dyno instances before stopping the other ones. Doesn't look like it's having negative side effects, but something to look into.

**Comment by dcloud** [comment]
See also https://github.com/ui/rq-scheduler/issues/70. There is an open pull request that could quiet this.

**Comment by realnot** [comment]
Each time I deploy an application Sentry return this error. How did you solved?

**Comment by shvng** [comment]
having same issue that @realnot is facing . Using docker container
